- template: lockdown
  description: Disables telnet on a network device
  device_types:
  - router
  - switch
  id: ba0c7f6b1b6552683caddc578efb4813
  name: Telnet disable
  platform: IOS
- template: lockdown
  description: SSH version 2 is enabled on a network device
  device_types:
  - router
  - switch
  id: 9b462685c56fde6bcbda0615b1f4a250
  name: SSH Version 2
  platform: IOS
- template: lockdown
  description: Disables the HTTP server on a network device
  device_types:
  - router
  - switch
  id: b931a90f7782a1cd205a177ec37b4255
  name: Disable HTTP server
  platform: IOS
- template: vtp
  description: VTP version 3 must be enabled on all switches
  device_types:
  - switch
  id: 08b0bfd388e774159a8119645127e90b
  name: VTP Version 3
  platform: IOS
- description: Disables IP domain lookup on a network device
  device_types:
  - router
  - switch
  id: 7d1f5bf3dd2c1946514214b407b6ec54
  name: Disable Domain lookup
  platform: IOS
- template: lockdown
  description: Disables IP domain lookup on a network device
  device_types:
  - router
  - switch
  id: 7d1f5bf3dd2c1946514214b407b6ec54
  name: Disable Domain lookup
  platform: IOS
